on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run the action
      id: logs 
      uses: ./
      with:
        myInput: 'Ben'
    - name: Revision Version 
      run: |
        echo "The linux revision is:"
        echo ${{ steps.logs.outputs.revision }}
    - name: Output Memory
      run : |
        echo "Memory info:"
        echo ${{ steps.logs.outputs.memory }}
